language: node_js

node_js:
 - "9.9.0"

install:
  - npm install --save-dev mocha
  - npm install --save-dev chai
  - npm install --save-dev chai-http

  - npm install --save-dev codecov
  - npm install --save-dev istanbul

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
  - codecov -t bffb0e55-cb81-490c-a8db-0c7308611d1f

after_success:
  - npm run uTest

env:
  global:
    - NODE_ENV=test