language: node_js
node_js:
 - "9.9.0"

env:
  global:
    - CODECOV_TOKEN=:"bffb0e55-cb81-490c-a8db-0c7308611d1f"

script:
- bash <(curl -s https://codecov.io/bash) -cF node_js


#after_script:
#- npm run covecov

#services:
#  - postgresql

# en json "coveralls": "npm run cover -- --report lcovonly && cat ./coverage/lcov.info | coveralls"
